name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: '<h1>It''s great having you contribute to this project</h1> Welcome to the community.'
        pr-message: '<h1>It''s great having you contribute to this project</h1> <h3>Welcome to the community.</h3> <h4>If you would like to continue contributing to open source and would like to do it with an awesome inclusive community, you should join our <a href="https://discord.gg/up4JGVbZ8G">Discord Server</a> and our <a href="https://chat.whatsapp.com/CVrBjAtYqxs6d7GFqZmhrR">WhatsApp Group</a> - we help and encourage each other to contribute to open source little . Any questions let us know.</h4>'
